services:
  # ── PROD ── (branch: main)
  - type: web
    name: prashanth-app-beerstore
    runtime: node
    plan: starter
    branch: main
    autoDeploy: true
    buildCommand: npm install && npm --prefix backend install && npm --prefix frontend install && npm --prefix frontend run build
    startCommand: node backend/server.js
    healthCheckPath: /api/health
    disk:
      name: prashanth-app-beerstore-data
      mountPath: /var/data/beerstore
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: JWT_SECRET
        value: BeerStore_PROD_2026_Key
      - key: ENV_NAME
        value: prod
      - key: DATA_DIR
        value: /var/data/beerstore

  # ── STG ── (branch: release)
  - type: web
    name: prashanth-app-beerstore-stg
    runtime: node
    plan: starter
    branch: release
    autoDeploy: true
    buildCommand: npm install && npm --prefix backend install && npm --prefix frontend install && npm --prefix frontend run build
    startCommand: node backend/server.js
    healthCheckPath: /api/health
    disk:
      name: prashanth-app-beerstore-stg-data
      mountPath: /var/data/beerstore
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: JWT_SECRET
        value: BeerStore_STG_2026_Key
      - key: ENV_NAME
        value: stg
      - key: DATA_DIR
        value: /var/data/beerstore
      - key: RESET_DEFAULT_ADMIN_PASSWORD
        value: true

  # ── QA1 ── (branch: qa)
  - type: web
    name: prashanth-app-beerstore-qa1
    runtime: node
    plan: starter
    branch: qa
    autoDeploy: true
    buildCommand: npm install && npm --prefix backend install && npm --prefix frontend install && npm --prefix frontend run build
    startCommand: node backend/server.js
    healthCheckPath: /api/health
    disk:
      name: prashanth-app-beerstore-qa1-data
      mountPath: /var/data/beerstore
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: JWT_SECRET
        value: BeerStore_QA1_2026_Key
      - key: ENV_NAME
        value: qa1
      - key: DATA_DIR
        value: /var/data/beerstore
      - key: RESET_DEFAULT_ADMIN_PASSWORD
        value: true

  # ── DEV1 ── (branch: develop)
  - type: web
    name: prashanth-app-beerstore-dev1
    runtime: node
    plan: starter
    branch: develop
    autoDeploy: true
    buildCommand: npm install && npm --prefix backend install && npm --prefix frontend install && npm --prefix frontend run build
    startCommand: node backend/server.js
    healthCheckPath: /api/health
    disk:
      name: prashanth-app-beerstore-dev1-data
      mountPath: /var/data/beerstore
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: JWT_SECRET
        value: BeerStore_DEV1_2026_Key
      - key: ENV_NAME
        value: dev1
      - key: DATA_DIR
        value: /var/data/beerstore
      - key: RESET_DEFAULT_ADMIN_PASSWORD
        value: true
