services:
  - type: web
    name: prashanth-app-beerstore
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 20
